name: Docker Image CI

on:
  push:
    branches: ["homol"]
  pull_request:
    branches: ["homol"]

jobs:
  build_homol:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag projeto-ac2-eng-software:$(date +%s)
